steps:
  # 1. On active l'API Cloud Functions
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args: ['gcloud', 'services', 'enable', 'cloudfunctions.googleapis.com']

  # 2. On active l'API Cloud Resource Manager
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args: ['gcloud', 'services', 'enable', 'cloudresourcemanager.googleapis.com']

  # 3. Étape de déploiement (sans la ligne allow-unauthenticated)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - 'gcloud'
      - 'functions'
      - 'deploy'
      - 'nutria_api'
      - '--runtime=python311'
      - '--trigger-http'
      - '--region=europe-west1'
      - '--entry-point=nutria_api'
    dir: 'backend-python'

options:
  logging: CLOUD_LOGGING_ONLY