steps:
  # 1. Enable the Cloud Functions API
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args: ['gcloud', 'services', 'enable', 'cloudfunctions.googleapis.com']

  # 2. Enable the Cloud Resource Manager API
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args: ['gcloud', 'services', 'enable', 'cloudresourcemanager.googleapis.com']

  # 3. Deployment step (restricted access, 'allow-unauthenticated' is purposely omitted)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - 'gcloud'
      - 'functions'
      - 'deploy'
      - 'nutria_api'
      - '--runtime=python311'
      - '--trigger-http'
      - '--region=europe-west1'
      - '--entry-point=nutria_api'
    dir: 'backend-python'

options:
  logging: CLOUD_LOGGING_ONLY